import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import Content from "@/components/Content/Content";
import { inter } from "./font";

export const metadata: Metadata = {
  title: "SEGHROUCHNI Youssef | Full Stack Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProvider>
          <Content>{children}</Content>
        </AppProvider>
      </body>
    </html>
  );
}
