import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import Content from "@/components/Content/Content";
import { inter } from "./font";
import { isMobileDevice } from "@/libs/isMobileDevice";
import cx from "classnames";

export const metadata: Metadata = {
  title: "SEGHROUCHNI Youssef | Full Stack Web Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const isMobile = isMobileDevice();

  return (
    <html lang="en">
      <body className={cx(inter.className)}>
        <AppProvider isMobileServer={isMobile}>
          <Content>{children}</Content>
        </AppProvider>
      </body>
    </html>
  );
}
